# Generated by Django 4.1.4 on 2022-12-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_mn',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_mn',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_mn',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='name_mn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_mn',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_mn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='description_mn',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='name_mn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
