# Generated by Django 4.1.4 on 2022-12-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0004_comment_comment_mn_faq_question_mn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('name_mn', models.CharField(blank=True, max_length=100, null=True)),
                ('description_uz', models.TextField(blank=True, max_length=3000, null=True)),
                ('description_ru', models.TextField(blank=True, max_length=3000, null=True)),
                ('description_en', models.TextField(blank=True, max_length=3000, null=True)),
                ('description_mn', models.TextField(blank=True, max_length=3000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_mn',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
