# Generated by Django 4.1.4 on 2022-12-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0005_partner_faq_answer_mn'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
