# Generated by Django 4.1.4 on 2023-01-07 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0006_slider_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='ServiceCategory',
        ),
    ]
